package com.example.phonetolinux

import com.example.phonetolinux.EndpointHandler
import com.example.phonetolinux.EndpointResponse
import android.content.Context
import com.example.phonetolinux.HttpUtils

/**
 * Represents the response generated by an endpoint plugin.
 */
data class EndpointResponse(val statusCode: String = "200 OK", val body: String)

/**
 * Common interface for all HTTP server endpoint plugins.
 * Each new server functionality should implement this interface.
 */
interface EndpointHandler {
    /** The URL path that this endpoint responds to (e.g., "/ping") */
    val path: String

    /** Main function executing the endpoint logic */
    fun handle(requestLine: String, context: Context): EndpointResponse
}